#![allow(
    dead_code,
    clippy::unreadable_literal,
    clippy::redundant_static_lifetimes
)]

// This file is automatically generated. Do not edit.

pub mod general_category;
pub mod property_bool;
